version: '3'

services:
  riskiwww:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: riskiwww
    volumes:
      - .:/riskiwww
    ports:
      - "8000:8000"
  compass:
    image: antonienko/compass-watch
    command: watch --poll /riskiwww/mybulma/
    volumes:
      - .:/riskiwww